- name: Zip Files
  hosts: all 
  become: yes
  tasks:
    - name: Compress directory
      command: |
        zip -r "/home/awxhost/app_data/archive-{{ ansible_date_time.date }}-{{ ansible_date_time.time }}.zip" "/home/awxhost/app_data"
      register: zip_result

    - name: Display zip file name
      debug:
        msg: "Zip file created: {{ zip_result.stdout }}"
