- name: Backup Files
  hosts: all
  become: yes
  tasks:
    - name: Create backup directory if not exists
      file:
        path: "/opt/backup"
        state: directory
        mode: '0755'

    - name: Create backup with timestamp
      shell: |
        tar -czf /opt/backup/backup-$(date +%Y%m%d-%H%M%S).tar.gz /home/awxhost/documents

    - name: Remove old backups
      shell: |
        find /opt/backup/ -type f -mtime +7 -delete
