- name: Zip Files
  hosts: all
  become: yes
  tasks:
    - name: Compress directory
      command: "zip -r /home/awxhost/app_data/archive-{{ ansible_date_time.date }}-{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}{{ ansible_date_time.second }}.zip /home/awxhost/app_data"
