- name: Check disk usage
  hosts: all
  tasks:
    - name: Run df command to check disk usage
      command: df -h
      register: disk_usage

    - name: Display disk usage
      debug:
        msg: "{{ disk_usage.stdout_lines }}"
