- name: Zip Files
  hosts: all
  become: yes
  tasks:
    - name: Compress directory
      archive:
        path: "/home/awxhost/app_data"
        dest: "/home/awxhost/app_data/archive-$(date +%Y%m%d-%H%M%S).zip"
        format: zip
